# Generated by Django 3.2.9 on 2021-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_features_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='some string', max_length=550),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='some string', max_length=150),
        ),
    ]
